# build_spdf_homebrew - build security practices data frame from data generated by SPEFTools.rb scripts
build_spdf_homebrew <- function(projCLOC,projVulns,path_commits)
{
    clocbyProjectMonth <- group_by(projCLOC,ProjectMonth)
    projSLOC <- summarise(clocbyProjectMonth,SLOC=sum(nCode))
    projSLOCRow <- summarise(clocbyProjectMonth,Factor="SLOC",Value=sum(nCode))

    projCommitsData <-     read.csv(path_commits,sep=";",col.names=c("hash","date","author","email","added","changed","pathname"))
    projCommitsData$date <- as.Date(projCommitsData$date)
    projCommitsData$ProjectMonth <- projectdate(projCommitsData$date)
    projCommitsData$added <- as.numeric(projCommitsData$added)
    projCommitsData$changed <- as.numeric(projCommitsData$changed)
    projCommitsData$author <- as.character(projCommitsData$author)
    projCommitsData$email <- as.character(projCommitsData$email)

    CommitsByProjectMonth <- group_by(projCommitsData,ProjectMonth)
    projCommits <- as.data.frame(summarise(CommitsByProjectMonth,cfCommits=length(unique(hash))))
    projCommitsRow <- data.frame(ProjectMonth=projCommits$ProjectMonth,Factor="Commits",Value=projCommits$cfCommits)

    projChurn <- as.data.frame(summarise(CommitsByProjectMonth,cfChurn=sum(added+changed)))
    projChurnRow <- data.frame(ProjectMonth=projChurn$ProjectMonth,Factor="Churn",Value=projChurn$cfChurn)

    projDevs <- as.data.frame(summarise(CommitsByProjectMonth,cfDevs=length(unique(author))))
    projDevsRow <- data.frame(ProjectMonth=projDevs$ProjectMonth,Factor="Devs",Value=projDevs$cfDevs)
    projCLOC$ProjectMonth <- as.Date(projCLOC$ProjectMonth)

    spdf <- projSLOCRow
    spdf <- rbind(spdf,projCommitsRow)
    spdf <- rbind(spdf,projChurnRow)
    spdf <- rbind(spdf,projDevsRow)

    # generate one column data frame containing all project months
    projTimeline <- unique(as.data.frame(projCommits[c("ProjectMonth")],drop=FALSE))
    # Needs $ProjectMonth: projTimeline <- seq(from=as.Date("2001-05-01"),to=as.Date("2015-11-01"),by='month')

    # align partial data with project timeline
    projV <- merge(projTimeline,projVulns,all.x=TRUE)
    projV$Value <- ifelse(is.na(projV$Value), 0, projV$Value)
    projV$Factor <- ifelse(is.na(projV$Factor), "Vulns", projV$Factor)
    projV$ProjectMonth <- as.Date(projV$ProjectMonth)
    # cumulative
    projVC <- projV
    projVC$Factor <- "TotalVulns"
    projVC$Value <- cumsum(projVC$Value)
    projVC$ProjectMonth <- as.Date(projVC$ProjectMonth)

    # computing a new Factor/Value combination from existing Factor/Values
    projCLOC$ProjectMonth <- as.Date(projCLOC$ProjectMonth)
    tmpSeries <- merge(projSLOC,projVC)
    tmpSeries$Value <- tmpSeries$Value/(tmpSeries$SLOC/1000)
    tmpSeries$Factor <- "VDensity"
    tmpSeries <- tmpSeries[c("ProjectMonth","Factor","Value")]
    spdf <- rbind(spdf,tmpSeries)
    return(spdf)
    }